source ~/.antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundles <<EOBUNDLES
git
lein
command-not-found
ruby
rails
rake
gem
node
zsh-users/zsh-syntax-highlighting
EOBUNDLES

# Load the theme.
antigen theme jeremyFreeAgent/oh-my-zsh-powerline-theme powerline

# Tell antigen that you're done.
antigen apply

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
  PATH="$HOME/bin:$PATH"
fi

alias o=xdg-open

autoload -U zmv

# https://github.com/rust-lang-nursery/rustup.rs#enable-tab-completion-for-bash-fish-or-zsh
fpath+=~/.zfunc

# http://boredzo.org/blog/archives/2016-08-15/colorized-man-pages-understood-and-customized
man() {
    env \
        LESS_TERMCAP_mb=$'\e[1;34m' \
        LESS_TERMCAP_md=$'\e[1;34m' \
        LESS_TERMCAP_me=$'\e[0m' \
        LESS_TERMCAP_se=$'\e[0m' \
        LESS_TERMCAP_so=$'\e[1;40;92m' \
        LESS_TERMCAP_ue=$'\e[0m' \
        LESS_TERMCAP_us=$'\e[1;32m' \
            man "$@"
}
