source ~/.antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundles <<EOBUNDLES
git
lein
command-not-found
ruby
rails
rake
gem
node
zsh-users/zsh-syntax-highlighting
EOBUNDLES

# Load the theme.
antigen theme jeremyFreeAgent/oh-my-zsh-powerline-theme powerline

# Tell antigen that you're done.
antigen apply

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
  PATH="$HOME/bin:$PATH"
fi

alias o=xdg-open
